string robot_id

int32 model_id		# Robot model ID
string model_name	# Robot model name
int32 type         		# Robot type: TYPE_AGF=0, TYPE_AGV=1, TYPE_AMR=2
float64 max_v		# Maximum linear velocity  (m/s)
float64 max_w		# Maximum angular velocity (deg/s)
float64 battery_life	# Robot battery life   (s)
float64 weight		# Robot weight         (kg)
float64 max_weight	# Robot maximum weight (kg)
float64 size_w		# Robot size [w, h, d] (m)
float64 size_h
float64 size_d
float64 task_time